name: Test push to dev slot

on:
    pull_request:
      types:  [opened, synchronize, reopened ]
      branches:
        - dev
  
jobs:
    test-pull-request:
        if: github.event.pull_request.merged == false
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install dependencies
          run: npm ci
        
        - name: Run tests
          run: npm run lint && npm run test